services:

    # Webserver service configuration
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: unidadesprod
        ports:
            - "8003:80"
        networks:
            - app_networkkup
        environment:
            - APP_URL=https://avizor.atomustechnologies.com/
            - ASSET_URL=https://avizor.atomustechnologies.com/
            - PATH_URL=https://avizor.atomustechnologies.com/
            - APP_DOMAIN=avizor.atomustechnologies.com
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3309
            - DB_DATABASE=unisistomprod
            - DB_USERNAME=root
            - DB_PASSWORD=Ulis2025!tom
            - APP_TIMEZONE=America/Mexico_City
            - APP_LOCALE=es
            - APP_FALLBACK_LOCALE=es_MX
            - APP_FAKER_LOCALE=es_MX
            
        depends_on:
            - db
                

    # Database service configuration
    db:
        image: mysql:8.0
        container_name: db_unidadesprod
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Ulis2025!tom
            MYSQL_DATABASE: unisistomprod
            MYSQL_TCP_PORT: 3309
        volumes:
            - db_dataprd:/var/lib/mysql
            
        ports:
            - 3309:3309
        expose:
            - 3309
        networks:
            - app_networkkup # Create a database named "todos"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadminunidadesprod
        environment:
            PMA_HOST: db
            PMA_PORT: 3309
            PPMA_USER: root
            PMA_PASSWORD: Ulis2025!tom
        ports:
            - "8383:80"
        depends_on:
            - db
        networks:
            - app_networkkup
        volumes:
            - ./.docker/php/zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

networks:
  app_networkkup:
    driver: bridge

volumes:
  db_dataprd: