services:

    # Webserver service configuration
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: unidades
        ports:
            - "8000:80"
        networks:
            - app_network
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=unisistom
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db    

    # Database service configuration
    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: unisistom
        ports:
            - "3306:3306"
        networks:
            - app_network # Create a database named "todos"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - app_network
        volumes:
            - ./.docker/php/zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

networks:
  app_network:
    driver: bridge

# Define a named volume for MySQL data storage
volumes:
    data: